### ISSUE TITLE
server closed the connection unexpectedly

### ISSUE THREAD

**Issue by jonathansimmons** [PostgresApp/PostgresApp#296]
I have a new dev we are trying to setup in our rails app and we are eternally getting the following error. When trying to create a db using a rails migration and postgres.app

He is running a 10.10 box. We don't get this error on other dev running 10.11 but I'm not sure how relevant that is. 

If this is a rails issue let me know and I'll move the problem there. Any info on how we might fix this would be appreciated. 

```bash
server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `initialize'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `new'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `connect'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:87:in `connection'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/tasks/postgresql_database_tasks.rb:8:in `connection'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/tasks/postgresql_database_tasks.rb:17:in `create'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:93:in `create'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:107:in `block in create_current'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:275:in `block in each_current_configuration'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:274:in `each'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:274:in `each_current_configuration'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:106:in `create_current'
/Users/50N6/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/railties/databases.rake:17:in `block (2 levels) in <top (required)>'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/50N6/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/50N6/.rvm/rubies/ruby-2.2.3/bin/rake:37:in `<main>'

Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "database"=>"sample_db", "host"=>"localhost", "pool"=>5, "timeout"=>5000}

```

cc: @songdavid

**Comment by jakob** [comment]
1) Did you have a look at the PostgreSQL server log file? It's in the data directory.

2) Does connecting with psql work?

3) Does your dev have some firewall or other protection / filtering software installed on his Mac?

**Comment by jonathansimmons** [comment]
1.) The log file is mostly empty and wasn't too helpful. It's listed below in it's entirety 

2.) psql does seem to work fine
  - I have a feeling the log details are just entries for work I did starting and stopping psql. (I attempted to manually create the db which you'll see did work and was logged worked)

3.) No known firewall or other filtering. 

I appreciate the help.
```bash
LOG:  database system was shut down at 2015-12-14 21:27:26 MST
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-14 21:35:48 MST
LOG:  MultiXact member wraparound protections are now enabled
LOG:  autovacuum launcher started
LOG:  database system is ready to accept connections
ERROR:  syntax error at or near "50" at character 37
STATEMENT:  CREATE DATABASE donations_dev owner=user_name_removed;
LOG:  received fast shutdown request
LOG:  aborting any active transactions
FATAL:  terminating connection due to administrator command
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-15 17:36:50 MST
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-15 17:47:47 MST
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-15 17:49:21 MST
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down

```

**Comment by jonathansimmons** [comment]
FWIW Everything works fine for other devs who are running 10.11. Not sure how/if the OS X version would come into play.

**Comment by jakob** [comment]
I'm stumped. "server closed the connection unexpectedly" points to a network problem, especially since the PostgreSQL server doesn't seem to report any errors. I really have no good idea what could be going on, but here are some things I would try to do:

1) Turn up the log level to debug in postgresql.conf, then you'll see if ruby even reaches the PostgreSQL server, or if the lost connection happens before.

2) Try to find out what server/port ruby is really trying to connect to. Maybe it's trying to connect to some other service on your Mac. I'm not too familiar with ruby, so I can't really help there.

3) Double check for any software on your Mac that may interfere with your network stack. Firewalls, filters, kernel extensions, ad blocking proxies, virtual network interfaces, etc. In my experience, most network issues are caused by software other than PostgreSQL interfering with the network.

4) [Uninstall Postgres.app](http://postgresapp.com/documentation/install.html), restart your Mac, reinstall Postgres.app, ensure that your Path [is configured correctly](http://postgresapp.com/documentation/cli-tools.html), then [reinstall the pg gem](http://postgresapp.com/documentation/configuration-ruby.html).

**Comment by jakob** [comment]
Postgres.app should work fine on 10.10; I don't think this is the problem.

**Comment by jakob** [comment]
Did you find the cause for this issue? Do you have any other questions, or can I close it?

**Comment by jonathansimmons** [comment]
I'm so sorry, I thought I'd closed this already. 

I was unable to find a solid reason. Having the dev update to 10.11 and creating a new postgres user/password helped but he still randomly get's disconnects. 

Regardless this is not a postgres.app issue.

**Comment by jakob** [comment]
Thanks for the update!
