### ISSUE TITLE
postgresApp command line

### ISSUE THREAD

**Issue by frans4** [PostgresApp/PostgresApp#339]
sudo ARCHFLAGS="-arch x86_64" gem install pg
 This line loads an error in my terminal 

```
Error loading RubyGems plugin "/Users//.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/executable-hooks-1.3.2/lib/rubygems_plugin.rb": dlopen(/Users//.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin15/openssl.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users//.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin15/openssl.bundle
  Reason: image not found - /Users//.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin15/openssl.bundle (LoadError)
Error loading RubyGems plugin "/Users//.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/gem-wrappers-1.2.7/lib/rubygems_plugin.rb": dlopen(/Users/SteveFrancois/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin15/openssl.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users//.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin15/openssl.bundle
  Reason: image not found - /Users//.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin15/openssl.bundle (LoadError)
/Users/SteveFrancois/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/Users//.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users//.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin15/psych.bundle, 9): Library not loaded: /usr/local/opt/libyaml/lib/libyaml-0.2.dylib (LoadError)
  Referenced from: /Users//.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin15/psych.bundle
  Reason: image not found - /Users//.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin15/psych.bundle
    from /Users//.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users//.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/psych.rb:7:in `<top (required)>'
    from /Users//.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users//.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users//.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/yaml.rb:6:in `<top (required)>'
    from /Users//.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/SteveFrancois/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/SteveFrancois/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems.rb:628:in `load_yaml'
    from /Users/SteveFrancois/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/config_file.rb:326:in `load_file'
    from /Users/SteveFrancois/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/config_file.rb:198:in `initialize'
    from /Users/SteveFrancois/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/gem_runner.rb:75:in `new'
    from /Users/SteveFrancois/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/gem_runner.rb:75:in `do_configuration'
    from /Users/SteveFrancois/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/gem_runner.rb:40:in `run'
    from /Users/SteveFrancois/.rvm/rubies/ruby-2.3.0/bin/gem:21:in `<main>'
MacBookProV2-65:~ SteveFrancois$ 

```

**Comment by jakob** [comment]
1) What error?
2) What version of Postgres.app are you using
3) What version of OS X are you using?

**Comment by frans4** [comment]
it says 2.000 but I have an app running 2.5.

**Comment by jakob** [comment]
Looks like your Ruby installation is broken. Looks like it's linked against two libraries built by homebrew (OpenSSL and libYAML) that have disappeared. Might have happened when you upgraded OS X.

Try reinstalling Ruby.

**Comment by frans4** [comment]
Ive reinstalled ruby and now I get this

 bundle exec rake db:create db:migrate
Could not locate Gemfile or .bundle/ directory

**Comment by frans4** [comment]
its says my path is not correctly setup

**Comment by jakob** [comment]
To be honest, I'm not really that familiar with Ruby, and I don't really know where that problem is coming from. Maybe you're in the wrong directory?

Here's how to set up the PATH for Postgres.app: http://postgresapp.com/documentation/cli-tools.html -- but I don't think this would solve your issue :(

**Comment by cappert** [comment]
```
9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
...
/Users/SteveFrancois/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/yaml.rb:5:in '<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
```
looks like you're missing a bunch of unrelated dependencies (ssl, libyaml) for Ruby, unrelated to Postgres.app.
