### ISSUE TITLE
failed to verify "trust" authentication

### ISSUE THREAD

**Issue by andriesfc** [PostgresApp/PostgresApp#777]
I get this every now and then:

```
Caused by: java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: FATAL: Postgres.app failed to verify "trust" authentication
  Hint: You may be able to connect by editing app permission in Postgres.app settings. Please report this error to https://github.com/PostgresApp/PostgresApp/issues
	at com.sun.gjc.spi.base.DataSource.getConnection(DataSource.java:115)
	at oracle.toplink.essentials.jndi.JNDIConnector.connect(JNDIConnector.java:130)
	... 102 more
```

**Comment by jakob** [comment]
Thanks for reporting this!

There should be a bit more info in the server log. Can you copy-paste the full error message from the server log?

Does stopping and starting the PostgreSQL server fix the issue?

**Comment by larrybolt** [comment]
> Thanks for reporting this!
> 
> There should be a bit more info in the server log. Can you copy-paste the full error message from the server log?
> 
> Does stopping and starting the PostgreSQL server fix the issue?

Restarting the server did solved an issue with same error message for me, thanks!
![CleanShot 2024-10-24 at 13 57 37@2x](https://github.com/user-attachments/assets/bd7b7b97-9757-4e05-92f5-19e5e778d3e5)

**Comment by andriesfc** [comment]
The log was not very help 
full. But I will attach the log for part of the 22nd 23'rd (as I mostly leave my laptop). 

[postgres.log.txt](https://github.com/userattachments/files/17522951/postgres.log.txt)

**Comment by tbussmann** [comment]
Glad that restarting the Server resolved the issue for you. 

Unfortunately, attaching the logfile did not work properly - it returns `Not Found`. You can easily access the Postgres log file by selecting "Open" under "Log File:" in the sheet opened by clicking on the "Server Settings..." button under the server in question:

![Bildschirmfoto 2024-11-06 um 18 06 39](https://github.com/user-attachments/assets/244c2ab4-b5c3-4837-a36f-cc47ea77b34c)
